### ISSUE TITLE
大佬，这个问题能修一下吗？我没有开启任何通知，报这个错

### ISSUE THREAD

**Issue by TimeBye** [raindrop-hb/tencent-video#5]
```
Traceback (most recent call last):
  File "/ql/data/scripts/raindrop-hb_tencent-video/index.py", line 117, in <module>
    main()
  File "/ql/data/scripts/raindrop-hb_tencent-video/index.py", line 110, in main
    ten_video(user['tag'],user['vdevice_qimei36'],user['vqq_appid'],user['vqq_openid'],user['vqq_access_token'],user['vqq_vuserid'],user['main_login'])
  File "/ql/data/scripts/raindrop-hb_tencent-video/index.py", line 84, in ten_video
    print(push.main(log))
  File "/ql/data/scripts/raindrop-hb_tencent-video/push.py", line 109, in main
    WeCom(content)
  File "/ql/data/scripts/raindrop-hb_tencent-video/push.py", line 36, in WeCom
    wx = config()["push"]["WeCom"]
  File "/ql/data/scripts/raindrop-hb_tencent-video/push.py", line 30, in config
    account=eval(account)
  File "<string>", line 3
    "v }
    ^
SyntaxError: unterminated string literal (detected at line 3)
```

大佬，这个问题能修一下吗？我没有开启任何通知，报这个错

**Comment by qingfeng11111** [comment]
我也是，报错代码好像是一样的。青龙推送不了，设置了推送报这个
![Uploading 233809020-f6e982cb-694b-4940-aa32-fd20f25c427d.jpg…]()

**Comment by qingfeng11111** [comment]
我也是，报错代码好像是一样的。青龙推送不了，设置了推送报这个
![233809020-f6e982cb-694b-4940-aa32-fd20f25c427d](https://user-images.githubusercontent.com/108140460/235199915-d829cf51-6182-4656-9f70-96c4e948d831.jpg)

**Comment by raindrop-hb** [comment]
> 我也是，报错代码好像是一样的。青龙推送不了，设置了推送报这个 ![233809020-f6e982cb-694b-4940-aa32-fd20f25c427d](https://user-images.githubusercontent.com/108140460/235199915-d829cf51-6182-4656-9f70-96c4e948d831.jpg)
你是什么时候git的

**Comment by qingfeng11111** [comment]
刚刚又重新git了一遍。还是报那个。青龙2.15.12。配置文件和脚本里都填了pushtoken

**Comment by raindrop-hb** [comment]
> 刚刚又重新git了一遍。还是报那个。青龙2.15.12。配置文件和脚本里都填了pushtoken

已修复

**Comment by raindrop-hb** [comment]
> ```
> Traceback (most recent call last):
>   File "/ql/data/scripts/raindrop-hb_tencent-video/index.py", line 117, in <module>
>     main()
>   File "/ql/data/scripts/raindrop-hb_tencent-video/index.py", line 110, in main
>     ten_video(user['tag'],user['vdevice_qimei36'],user['vqq_appid'],user['vqq_openid'],user['vqq_access_token'],user['vqq_vuserid'],user['main_login'])
>   File "/ql/data/scripts/raindrop-hb_tencent-video/index.py", line 84, in ten_video
>     print(push.main(log))
>   File "/ql/data/scripts/raindrop-hb_tencent-video/push.py", line 109, in main
>     WeCom(content)
>   File "/ql/data/scripts/raindrop-hb_tencent-video/push.py", line 36, in WeCom
>     wx = config()["push"]["WeCom"]
>   File "/ql/data/scripts/raindrop-hb_tencent-video/push.py", line 30, in config
>     account=eval(account)
>   File "<string>", line 3
>     "v }
>     ^
> SyntaxError: unterminated string literal (detected at line 3)
> ```
> 
> 大佬，这个问题能修一下吗？我没有开启任何通知，报这个错

已修复，重新git
